### ISSUE TITLE
No Visible agent on Agent Breakdown dashboard (DT Client)

### ISSUE THREAD

**Issue by kumar4sun** [Dynatrace/Dynatrace-AppMon-Docker#19]
Hi All,

I am new to github and since i am familiar with DynaTrace i started exploring the option of deploying the APP Mon to monitor microservices running on my docker container.
I followed the instruction provided on readme however did not install any specific agent and installed  the license via client.
Doing that i am not seeing any connected agent. I have a microservice container built on spring boot running on docker that i want to monitor. Can i please get some help with this ?

**Comment by BlazejT** [comment]
Hi @kumar4sun ,
have you followed agents installation instruction from Dynatrace-Agent-Examples?

**Comment by kumar4sun** [comment]
Thanks for responding. This is where my confusion is. I looked at the examples and there are variety of it available at git hub for example :- glassfish,httpd,java,nginx and tomcat. I am not sure which one to use. I have a microservice built from Spring boot running on Ubuntu Docker container. are there any further instructions or information available on how to install and configure the Agent ?

**Comment by Dynatrace-Asad-Ali** [comment]
@kumar4sun 
I would be happy to walk you through the steps to instrument your app with AppMon agents. Please let me know a good way to reach you.

**Comment by kumar4sun** [comment]
@Dynatrace-Asad-Ali , Is it possible to help me tomorrow 12 PM tomorrow. Can you Please let me know how would you like to schedule this session ? I have a presentation coming up and would like to present a demo on our micro-services rather than on EasyTravel.

**Comment by Dynatrace-Asad-Ali** [comment]
@kumar4sun Yes, I do have time today (Friday) at noon EST. What is the best way to reach you?

**Comment by kumar4sun** [comment]
@Dynatrace-Asad-Ali  sorry i was pulled in to multiple meeting today. Is there anything you want me to try any instructions etc would help. right now i have done everything that visible in the readme the only leftover part is the agent configuration

**Comment by kumar4sun** [comment]
Can i please get some help with this issue ?

**Comment by BlazejT** [comment]
@kumar4sun, about your confusion - Agent component just runs the container with Agent libraries. Your task is configure them and/or run them, that's why there are some Agent examples. The Agent container does not run any Agents. You can configure them from WebServer UI as well if you'd like.

In case you haven't resolved the issue with Appmon Agents configuration with @Dynatrace-Asad-Ali , here are some guidelines:
https://www.dynatrace.com/support/doc/appmon/application-monitoring/agents/
https://www.dynatrace.com/support/doc/appmon/installation/install-agents/
https://www.dynatrace.com/support/doc/appmon/installation/set-up-agents/

PS. Please mind that we talk about Dynatrace *Appmon* Agents, not Dynatrace Agents/OneAgent.

Let us know if it helped.

**Comment by kumar4sun** [comment]
Thanks @BlazejT . I am going through the link and update you as soon as possible.

**Comment by kumar4sun** [comment]
@

**Comment by kumar4sun** [comment]
fol dsfdsf

**Comment by kumar4sun** [comment]
@

**Comment by kumar4sun** [comment]
@
